//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public int Id { get; set; }
        public string nama { get; set; }
        public Nullable<int> username { get; set; }
        public string deskripsi { get; set; }
        public Nullable<System.DateTime> tl { get; set; }
        public string alamat { get; set; }
        public string kontak { get; set; }
    
        public virtual akun akun { get; set; }
    }
}
